### ISSUE TITLE
if@Latin and \text

### ISSUE THREAD

**Issue by nolda** [persian-tex/bidi#3]
The `if@Latin` test appears to evaluate to false even in non-RTL context. Cf. the following MWE, involving AMSmath's `\text` command:

    \documentclass{article}
    \usepackage{amsmath}
    \usepackage{polyglossia}
    \setdefaultlanguage{english}
    \newfontfamily\hebrewfont[Script=Hebrew]{Linux Libertine O}
    \setotherlanguage{hebrew}

    \begin{document}
    $\text{A B C}$
     
    $\text{\textenglish{A B C}}$
     
    \textenglish{$\text{A B C}$}
     
    $\text{\texthebrew{א ב ג}}$
     
    \texthebrew{$\text{א ב ג}$}
    \end{document}

In TeX Live 2014, `A B C` always comes out as "C B A" in RTL direction, like the Hebrew text.

This is avoided by the following workaround in the document preamble:

    \makeatletter
    \def\if@Latin{\unless\if@RTL}
    \makeatother

**Comment by vafa** [comment]
This is not a bug of `bidi` package and your solution is nor right. `bidi` package provides `\if@Latin` package so a package like `polyglossia` sets it to false for RTL-based scripts and sets it to true for non-RTL-based scripts. I have several times discussed this with the author of `pologlossia` package. Therefore it is a bug of `polyglossia` and not `bidi` package.
