### ISSUE TITLE
bidi update breaks package soul

### ISSUE THREAD

**Issue by johannesbottcher** [persian-tex/bidi#3]
The following minimal working example breaks package `soul` with the latest update of `bidi` as reported on [goLateX](http://golatex.de/viewtopic,p,77131.html#77131):

```latex
\documentclass{article}
\usepackage{soul}
\usepackage{bidi}
\begin{document}
Dies ist ein Beispieltext! \ul{Dies ist ein Beispieltext! Dies
	ist ein Beispieltext! Dies ist ein Beispieltext! Dies ist
ein Beispieltext!}
\end{document}
```

temporary fix by a guest: 

```latex
\makeatletter
\def\bidi@RTL@everypar{\if@RTL{\setbox\z@\lastbox\beginR\ifvoid\z@\else\usebox\z@\fi}\fi}
\makeatother
```

**Comment by vafa** [comment]
This is `soul` issue and I do not consider it a `bidi` package bug. You can use `bidihl` package which does not have `soul` package problem.

**Comment by johannesbottcher** [comment]
Thank you, i'll send the information further.

**Comment by vafa** [comment]
Actually I added support for `soul` package and pushed version `18.1` of `bidi` package on CTAN (it is now on CTAN and you should be able to get it by updating your TeXLive in a few days). Therefore using `soul` package should be no problem.

However, if you are interested to look at alternative packages, you can use `ulem` package if you wish to underline your text:

````latex
\documentclass{article}
\usepackage{ulem}
\usepackage{bidi}
\begin{document}
Dies ist ein Beispieltext! \uline{Dies ist ein Beispieltext! Dies
    ist ein Beispieltext! Dies ist ein Beispieltext! Dies ist
ein Beispieltext!}
\end{document}
````
and if you want to highlight text, then you can use my `bidihl` package:

````latex
\documentclass{article}
\usepackage{bidihl}
\usepackage{bidi}
\begin{document}
Dies ist ein Beispieltext! \bidihl{Dies ist ein Beispieltext! Dies
    ist ein Beispieltext! Dies ist ein Beispieltext! Dies ist
ein Beispieltext!}
\end{document}
````

**Comment by johannesbottcher** [comment]
Thank you for the fix, i'll get the information to the OP on goLaTeX. 

Personally, i wouldn't dare to underline text. :-)
