### ISSUE TITLE
bidi 17.9 break paragraphed endnotes in reledmac.

### ISSUE THREAD

**Issue by maieul** [persian-tex/bidi#4]
As for soul (#3), bidi 17.9 breaks reledmac, for paragraphed endnotes.
See this MWE
`````
\listfiles
\documentclass{article}
\usepackage[no-math]{fontspec}
\usepackage{xltxtra,xunicode,amsmath}

\usepackage{polyglossia}
\setdefaultlanguage{french}

\usepackage[series={A,B}]{reledmac}
\Xarrangement[A,B]{paragraph}

\usepackage{bidi}

\makeatletter

%\def\bidi@RTL@everypar{\if@RTL{\setbox\z@\lastbox\beginR\ifvoid\z@\else\usebox\z@\fi}\fi}%Before uncomment it to obtain correct feature
%\def\bidi@RTL@everypar{{\setbox\z@\lastbox\if@RTL\beginR\else\fi\ifvoid\z@\else\fi}}%After
\begin{document}
\meaning\beginL
\meaning\beginR
\beginnumbering

\pstart

\edtext{Jean}{\Bfootnote{Paul}} a vu \edtext{Jean}{\Bfootnote{Paul}}.
\edtext{Jean}{\Bfootnote{Paul}} a vu \edtext{Jean}{\Bfootnote{Paul}}.
\edtext{Jean}{\Bfootnote{Paul}} a vu \edtext{Jean}{\Bfootnote{Paul}}.
\edtext{Jean}{\Bfootnote{Paul}} a vu \edtext{Jean}{\Bfootnote{Paul}}.
\edtext{Jean}{\Bfootnote{Paul}} a vu \edtext{Jean}{\Bfootnote{Paul}}.
\edtext{Jean}{\Bfootnote{Paul}} a vu \edtext{Jean}{\Bfootnote{Paul}}.

\pend

\endnumbering

\end{document}
``````

reported by @ralessi in https://github.com/maieul/ledmac/issues/421

**Comment by vafa** [comment]
That is natural and I do not consider it a bug since `TeX--XeT` data structures are different from TeX. I obviously will not be changing the definition of `\bidi@RTL@everypar` because it is supposed to be the way it is otherwise the command `\setLTR` in

```` latex
\input bidi
\setRTL

\hbox{\beginR\vbox{%
\setLTR
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
}\endR}

\bye
````

will have no effect. The `bidi` package `extrafootnotefeatures` and specifically `\paragraphfootnotes` command is broken with this new definition. It actually uses the same approach as the `ledmac` package.

The definition of `\paragraphfootnotes` needs to change so that it works with the new definition and I guess the same thing needs to be done with `ledmac` package.

**Comment by maieul** [comment]
and what should be the good approach ? because for now, I don't understand anything of why you did this modification and what does it mean (I don't know well the XeTeX feature). So I am not able, except with many loose of time, to correct the definition of paragraphed notes.

**Comment by vafa** [comment]
To be honest, I do not have a solution right now. I need to do some experiments and see what is happening exactly; I also need to talk to Peter Breitenlohner (author of etex) if it turns out to be a TeX--XeT bug. However, I will let you know as soon as I have a solution.

The main reasong for the change of the definition was my minimal example above; with the old definition, if a `\vbox` ended up in a right to left `\hbox`, then `\setLTR` would not have any effect. There was actually a question asked on tex.stackexchange: http://tex.stackexchange.com/questions/271752

In your minimal example, the problem is with `\beginR` or `\begnL`; because if you remove it from the definition of `\bidi@RTL@everypar`, then the issue goes away.

As I said above, when I find a solution, I will let you know immediately.

**Comment by maieul** [comment]
ok. nice. have a good test. I have send an email to the (r)(e)ledmac list to said them not to upload bidi yet. And I wait for your solution.

**Comment by vafa** [comment]
Thanks for your patience.

**Comment by maieul** [comment]
thanks for your work and you answer. For me, RTL management in reledmac is one of the most difficult aspect (especially because I must manage with both LuaTeX and XeTeX, which have not the same approach).

**Comment by vafa** [comment]
I was able to fix `\paragraph` footnotes of my `bidi` package. See this:

````latex
\documentclass{article}
\usepackage[extrafootnotefeatures]{bidi}
\makeatletter
\renewcommand{\@parafootnotetext}[1]{\insert\footinsv@r{\@RTLfalse
  \def\baselinestretch{\m@m@footnote@spacing}%
  \reset@font\foottextfont
  \@preamfntext
    \protected@edef\@currentlabel{%
       \csname p@footnote\endcsname\@thefnmark
    }%
    \color@begingroup
    \setbox0=\hbox{%
      \@makefntext{%
        \rule\z@\footnotesep\ignorespaces#1\@finalstrut\strutbox
        \penalty -10
        \hskip\m@mipn@skip
      }%
    }%
    \dp0=0pt \ht0=\footfudgefactor\wd0 \box0
    \color@endgroup}} 
\makeatother
\paragraphfootnotes
\begin{document}
\footnote{test 1}\footnote{test 2}\footnote{test 3}%
\footnote{test 4}\footnote{test 5}\footnote{test 6}%
\footnote{test 1}\footnote{test 2}\footnote{test 3}%
\footnote{test 1}\footnote{test 2}\footnote{test 3}%
\footnote{test 1}\footnote{test 2}\footnote{test 3}%
\end{document}
````

I think, you will need the same kind of modification to the `ledmac` package.

**Comment by maieul** [comment]
I have just look quickly to code, and compare to the previous one.
If I don't make any mistake, you have deleted the intermediate state with a \vbox, and come back to the original code where there is no vbox.

Hoever, if I read the commentaries added by my predecessor in ledmac code about this vbox, it is required for hyphenation.

``````
% The initial model for this insertion is, of course, the
% \verb"\insert\footins" definition in \thetexbook, p.\,398.
% There, the footnotes are first collected up in hboxes, and these
% hboxes are later unpacked and stuck together into a paragraph.
%
% However, Michael Downes\index{Downes, Michael} has pointed out
% that because text in hboxes gets typeset in restricted horizontal
% mode, there are some undesirable side-effects if you later want
% to break such text across lines.  In restricted horizontal mode,
% where \TeX\ does not expect to have to break lines, it does not
% insert certain items like \protect\cs{discretionary}s. If you later unbox
% these hboxes and stick them together, as the \texbook{}
% macros do to make these footnotes, you lose the ability to
% hyphenate after an explicit hyphen.  This can lead to overfull
% \protect\cs{hbox}es when you would not expect to find them, and to the
% uninitiated it might be very hard to see why the problem had
% arisen.\footnote{Michael Downes, `Line Breaking in \protect\cs{unhbox}ed
% Text', \textit{TUGboat} \textbf{11} (1990), pp.\,605--612.}
%
% Wayne Sullivan\index{Sullivan, Wayne} pointed out to us another
% subtle problem that arises from the same cause: \TeX\ also leaves
% the \protect\cs{language} whatsit nodes out of the horizontal
% list.\footnote{See \thetexbook, p.\,455 (editions after
% January 1990).}  So changes from one language to another will not
% invoke the proper hyphenation rules in such footnotes.  Since
% critical editions often do deal with several languages,
% especially in a footnotes, we really ought to get this bit of code
% right.
%
% To get around these problems, Wayne suggested emendations to the
% \texbook{} versions of these macros which are broadly the
% same as those described by Michael: the central idea (also
% suggested by Donald Knuth in a letter to Michael) is to avoid collecting
% the text in an \protect\cs{hbox} in the first place, but instead to collect
% it in a \protect\cs{vbox} whose width is (virtually)
% infinite.\label{hboxproblem} The text is therefore typeset in
% unrestricted horizontal mode, as a paragraph consisting of a
% single long line.  Later, there is an extra level of unboxing to
% be done: we have to unpack the \protect\cs{vbox}, as well as the hboxes
% inside it, but that is not too hard.  For details, we refer you to
% Michael's article, where the issues are clearly
% explained.\footnote{Wayne supplied his own macros to do this, but
% since they were almost identical to Michael's, Peter Wilson have used the
% latter's \protect\cs{Xunvxh} macro since it is publicly
% documented.}  Michael's unboxing macro is called \protect\cs{Xunvxh}: unvbox,
% extract the last line, and unhbox it.
`````` 

I am afraid some boarding effect happens if we suppress totaly this vbox.

**Comment by vafa** [comment]
Is there any side effect if you disable `\bidi@RTL@everypar` inside the `\vbox`?

````latex
\documentclass{article}
\usepackage[extrafootnotefeatures]{bidi}
\makeatletter
\renewcommand{\@parafootnotetext}[1]{\insert\footinsv@r{%
  \def\baselinestretch{\m@m@footnote@spacing}%
  \reset@font\foottextfont
  \@preamfntext
  \protected@edef\@currentlabel{%
    \csname p@footnote\endcsname\@thefnmark}%
  \setbox0=\vbox{\hsize=\maxdimen
   \let\bidi@RTL@everypar\@empty
    \color@begingroup
      \noindent \@parafootfmt{\if@RTL@footnote\beginR\else\beginL\fi#1\if@RTL@footnote\endR\else\endL\fi}%
    \color@endgroup}%
  \m@mungebox}\m@mmf@prepare}
\makeatother
\paragraphfootnotes
\begin{document}
\footnote{test 1}\footnote{test 2}\footnote{test 3}%
\footnote{test 4}\footnote{test 5}\footnote{test 6}%
\footnote{test 1}\footnote{test 2}\footnote{test 3}%
\footnote{test 1}\footnote{test 2}\footnote{test 3}%
\footnote{test 1}\footnote{test 2}\footnote{test 3}%
\end{document}
````

**Comment by maieul** [comment]
In your case no. In the case of reledmac, yes. I have spurious space. I don't know why. They should have something specific to (r)(e)ledmac. cf f6ff366

https://github.com/maieul/ledmac/commit/f6ff366756c12ba4b98c1af5b6e04c50460df2a4

but it something specifiy to reledmac. I have to look on it.

**Comment by maieul** [comment]
yes, it is something specific to my code. So for me this issue can be close.

**Comment by maieul** [comment]
thanks for your suggestion.

**Comment by vafa** [comment]
No worries. Anytime. I have applied the same in `bidi` and uploaded version 18.0 to CTAN.

**Comment by maieul** [comment]
I will do the same for reledmac to night. I have found the specific problem in reledmac : I have inserted a \leavevmode before outputing footnotes. It was to prevent problem with justification in rtl notes paragraphed notes. Maybe it is related to the question on the xetex list.

Cf https://github.com/maieul/ledmac/tree/14c3803bb441ea5c6fecd740582477bd300f0b6c
