### ISSUE TITLE
bug in tabular bidi: ignoring [t] option

### ISSUE THREAD

**Issue by Tim-at-AST** [persian-tex/bidi#6]
When using `bidi` and `tabulars` there is a bug because bidi ignores the [t] option in tabular when using non-english tabular.

I have two tabular side by side and I want their tops aligned.

When I use English language, it works fine.

When I use Arabic language, the tables suddenly become bottom-aligned, even though I used the [t] specification.

The following MWE shows this:

	\documentclass[10pt]{article}
	\usepackage{booktabs}
	\usepackage{polyglossia}
	\setmainlanguage{arabic}
	\setotherlanguage{english}
	\newfontfamily\arabicfont[Script=Arabic]{Times New Roman}
	\begin{document}

	\begin{tabular}[t]{rl} \toprule
	كلمة&كلمة\\ \midrule
	كلمة&كلمة\\
	\bottomrule
	\end{tabular}
	\hfill
	\begin{tabular}[t]{rl} \toprule
	كلمة&كلمة\\ \midrule
	كلمة&كلمة\\
	كلمة&كلمة\\
	كلمة&كلمة\\
	كلمة&كلمة\\
	\bottomrule
	\end{tabular}

	\begin{english}
	\begin{tabular}[t]{rl} \toprule
	word&word\\ \midrule
	word&word\\
	\bottomrule
	\end{tabular}
	\hfill
	\begin{tabular}[t]{rl} \toprule
	word&word\\ \midrule
	word&word\\
	word&word\\
	word&word\\
	word&word\\
	\bottomrule
	\end{tabular}
	\end{english}

	\end{document}

I wrote about this in [texs.tackexchange](http://tex.stackexchange.com/questions/276618/polyglossia-and-vertical-tabular-alignment/276631?noredirect=1#comment665942_276631) and it was egreg who found the bug.

He wrote:

> There is a bug in array-xetex-bidi.def, line 90

        \let\\\@arraycr \let\tabularnewline\\\let\par\@empty \if@RTLtab\hbox\bgroup\beginR\vbox\bgroup\fi\@preamble}

> To be more precise, the bug is in

          \if@RTLtab\hbox\bgroup\beginR\vbox\bgroup\fi

> which unconditionally inserts the table in a \vbox, making irrelevant the \vtop started with the [t] option.

Thank you

Tim

**Comment by vafa** [comment]
Hello Tim

Thanks for your bug report. I will fix this for the next version.

Your sincerely,
  Vafa
