### ISSUE TITLE
Problem with xecolor

### ISSUE THREAD

**Issue by bateni** [persian-tex/bidi#7]
The manual of bidi package mentions that linebreaks cause issues for the standard "color" package and one may instead use "xecolor" package.  The latter works great except that in XeTeX font color assigned via \addfontfeature does not seem to get inherited when the font changes.

Suppose I use \xecolor{blue} to change the color to blue.  Then any part of text that uses a new color switches back to black (or to the default for that font, when it was defined).  Is there a work-around for this?

**Comment by vafa** [comment]
Well, that is natural. Since color is the font attribute, whenever you change to a new font, the color will also reset so you will have to insert another `\xecolor{...}` command:

````tex
\documentclass{article}
\usepackage{xecolor}
\setmainfont{Times New Roman}
\newfontfamily\test{Arial}
\begin{document}
\xecolor{red}
This is a test as you can see
\test\xecolor{red}
This is another test as you can see
\end{document}
````

If you are happy using `\special` to color your text, then you may also use the following:

````tex
\documentclass{article}


\usepackage{fontspec}
\setmainfont[Script=Arabic]{Times New Roman}

\usepackage[RTLdocument]{bidi}

\makeatletter

\long\def\bidi@addto#1#2{\expandafter\def\expandafter#1\expandafter{#1#2}}

\bgroup \catcode`!=3 \catcode`?=3
\gdef\bidi@replacestrings#1#2{\long\def\bidi@replacestringsA##1#1##2!{%
   \ifx!##2!\bidi@addto\bidi@tmpb{##1}\else\bidi@addto\bidi@tmpb{##1#2}\bidi@replacestringsA##2!\fi}%
   \edef\bidi@tmpb{\expandafter}\expandafter\bidi@replacestringsA\bidi@tmpb?#1!%
   \long\def\bidi@replacestringsA##1?{\def\bidi@tmpb{##1}}\expandafter\bidi@replacestringsA\bidi@tmpb
}
\egroup



\newbox\bidi@color@start@box  \newbox\bidi@color@end@box
\setbox\bidi@color@start@box=\hbox{\special{color pop}}
\setbox\bidi@color@end@box=\hbox{\special{color push rgb 1 0 0}}%

\def\bidicolor#1{\def\bidi@tmpb{#1}\bidi@replacestrings{ }{\bidi@specialspace}%
   {\copy\bidi@color@start@box\bidi@tmpb\copy\bidi@color@end@box}%
}
\def\bidi@specialspace{%
   \discretionary{\copy\bidi@color@end@box}{\copy\bidi@color@start@box}{\kern\fontdimen2\font}%      
   \nobreak\hskip 0pt plus\fontdimen3\font minus\fontdimen4\font
}

\makeatother

\begin{document}
این یک متن معمولی است
\bidicolor{این متن با رنگ قرمز نوشته می‌شود که در یک سطر قرار می‌گیرد}
و این متن بعد آن است که به سطر بعد می‌رود و
\bidicolor{%
حالا یک متن رنگی می‌نویسیم که در چندین سطر قرار بگیرید تا کارایی رنگی کردن متن را ببینیم کنون ای خردمند وصف خرد          بدین جایگه گفتن اندرخورد
کنون تا چه داری بیار از خرد          که گوش نیوشنده زو برخورد
خرد بهتر از هر چه ایزد بداد          ستایش خرد را به از راه داد
خرد رهنمای و خرد دلگشای          خرد دست گیرد به هر دو سرای
ازو شادمانی وزویت غمیست          وزویت فزونی وزویت کمیست
خرد تیره و مرد روشن روان          نباشد همی شادمان یک زمان
چه گفت آن خردمند مرد خرد          که دانا ز گفتار از برخور
}
و ادامه متن که با رنگ سیاه نوشته می‌شود همانطوری که می‌بینید هیچ مشکلی ندارد و رنگ چکه نمی‌کند.
\end{document}
````

**Comment by bateni** [comment]
Thanks!  This is interesting.

But it does not work for multiparagraph arguments; even after making the definitions "long", there will be both leaks and uncolored pieces.

I tried the following:

\ExplSyntaxOn
\tl_new:N  \l__fix_color_cur_color_tl
\keys_define:nn { fix_color_color_parse }
      {
         Color .tl_set:N = \l__fix_color_cur_color_tl,
      }
\makeatletter
\cs_new:Nn \__fix_color_save_color:
{
        \tl_clear:N \l__fix_color_cur_color_tl
        \prop_get:cnN {g__fontspec_ \f@family _prop} {options} \l__fontspec_options_tl
        \keys_set_known:nV { fix_color_color_parse } { \l__fontspec_options_tl }
}
\makeatother
%
\tl_new:N \l__fix_color_old_color_tl
\cs_new:Nn \__fix_color_restore_color:
{
        \tl_set:Nf \l__fix_color_old_color_tl { \l__fix_color_cur_color_tl }
        \__fix_color_save_color:
        \tl_if_empty:NT { \l__fix_color_cur_color_tl }
        {
                \tl_if_empty:NF { \l__fix_color_old_color_tl }
                {
                        \addfontfeature{Color=\l__fix_color_old_color_tl}
                }
        }
}
%%
\newcommand{\ColorFont}[1]{
\expandafter\def\csname #1 Col \endcsname {
\__fix_color_save_color:
\csname #1 \endcsname
\__fix_color_restore_color:
}
}

\newfontfamily\Arial{Arial}
\newfontfamily\ArialGreen[Color=green]{Arial}
\ColorFont{Arial}
\ColorFont{ArialGreen}

Now, use of \ArialCol will inherit color from its surroundings while that for \ArialGreenCol does not because it has its own prefixed color.

There are a few issues here:
1) I need to define these \<FontName>Col commands that work as I wish (i.e., similar to \textcolor and \color in LaTeX).
2) Math mode does not inherit the color.

To address issue (1) I did the following.

\usepackage{etoolbox}
\pretocmd{\fontfamily}{\__fix_color_save_color:}{}{}
\apptocmd{\selectfont}{\__fix_color_restore_color:}{}{}

Now the color is automatically passed on, but it now leaks to footnotes as well.

My end goal is to get the exact same behavior of LaTeX \textcolor and \color commands in XeTeX.

**Comment by vafa** [comment]
> But it does not work for multiparagraph arguments; even after making the definitions "long", there will be both leaks and uncolored pieces.

It can be extended to cover that case too.

> I tried the following:
````tex
\ExplSyntaxOn
\tl_new:N \l__fix_color_cur_color_tl
\keys_define:nn { fix_color_color_parse }
{
Color .tl_set:N = \l__fix_color_cur_color_tl,
}
\makeatletter
\cs_new:Nn __fix_color_save_color:
{
\tl_clear:N \l__fix_color_cur_color_tl
\prop_get:cnN {g__fontspec_ \f@family _prop} {options} \l__fontspec_options_tl
\keys_set_known:nV { fix_color_color_parse } { \l__fontspec_options_tl }
}
\makeatother
%
\tl_new:N \l__fix_color_old_color_tl
\cs_new:Nn __fix_color_restore_color:
{
\tl_set:Nf \l__fix_color_old_color_tl { \l__fix_color_cur_color_tl }
__fix_color_save_color:
\tl_if_empty:NT { \l__fix_color_cur_color_tl }
{
\tl_if_empty:NF { \l__fix_color_old_color_tl }
{
\addfontfeature{Color=\l__fix_color_old_color_tl}
}
}
}
%%
\newcommand{\ColorFont}[1]{
\expandafter\def\csname #1 Col \endcsname {
__fix_color_save_color:
\csname #1 \endcsname
__fix_color_restore_color:
}
}

\newfontfamily\Arial{Arial}
\newfontfamily\ArialGreen[Color=green]{Arial}
\ColorFont{Arial}
\ColorFont{ArialGreen}
````
I am not familiar with LaTeX3 programming notation so I am afraid that I can not comment on your work!

> ... Math mode does not inherit the color.

You can not (unless your math is typeset using some OpenType fonts). `\color` or `\textcolor` (from `color` or `xcolor` packages) have no issues in math mode.

> To address issue (1) I did the following.
````tex
\usepackage{etoolbox}
\pretocmd{\fontfamily}{__fix_color_save_color:}{}{}
\apptocmd{\selectfont}{__fix_color_restore_color:}{}{}
````
Loading the `etoolbox` is not needed; if you are using the `bidi` package, then package `biditools` is loaded which offers `\bidi@pretocmd` and `\bidi@apptocmd` control sequences which work like `\pretocmd` and `\apptocmd`, respectively.

> Now the color is automatically passed on, but it now leaks to footnotes as well.

Which is natural.

> My end goal is to get the exact same behavior of LaTeX `\textcolor` and `\color` commands in XeTeX.

You can not; for instance, things like `\hrule` and `\vrule` can not be colored using XeTeX font color feature because they are not a glyph of the font being used.
