### ISSUE TITLE
Traditionalpoem

### ISSUE THREAD

**Issue by bateni** [persian-tex/bidi#8]
In the latest version for "bidi" package, it seems that "bidipoem" is not loaded by default.  This is not mentioned in the documentation.

**Comment by vafa** [comment]
`bidipoem` have never been loaded by the `bidi` package and you need to load it yourself by

````tex
\usepackage{bidipoem}
````
I close this since this is not really an issue.

**Comment by bateni** [comment]
I had not used the previous versions of bidi; that's why I said this happens in the latest version.

The behavior is perfectly normal.  I'm just saying the documentation of the package is confusing.  In the section on traditionalpoem, the user should be instructed to include that package; I could only figure it out after looking at the source code.

**Comment by vafa** [comment]
The documentation is really outdated; it has been more than five years that it has not been updated.
