### ISSUE TITLE
Problem with HEH glyphs

### ISSUE THREAD

**Issue by bateni** [persian-tex/bidi#9]
I don't know if this is a problem with Bidi or XeTeX or something else.  The problem happens when a font has a special glyph for isolated form for HEH (I guess, any standard Persian font including XB Yas):

U+FBAA: ARABIC LETTER HEH DOACHASHMEE ISOLATED FORM
U+FBAC: ARABIC LETTER HEH DOACHASHMEE INITIAL FORM

These two are used incorrectly.  The first one is used in place of the second one.  (Same thing may be happening for U+FBAB and U+FBAD but I have not tested it.)

The following show two examples using XB Yas.

<img width="90" alt="heh-1" src="https://cloud.githubusercontent.com/assets/6666981/11174122/b4baf9fe-8bed-11e5-9676-e87b09d9a836.png">
<img width="67" alt="heh-2" src="https://cloud.githubusercontent.com/assets/6666981/11174123/b4bdcbac-8bed-11e5-8767-7480ce4e6eb1.png">

I'm using XeTeX, Version 3.14159265-2.6-0.99992 (TeX Live 2015) on Max OS X with bidi package 2015/11/07, v18.2.

**Comment by vafa** [comment]
I am closing this issue since it is not related to the `bidi` package. You are best to ask this on HarfBuzz forum or something since that is the library xetex uses.
